# Generated by Django 4.2.4 on 2023-08-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='status',
            field=models.IntegerField(choices=[(1, 'active'), (2, 'inactive')], default=1),
        ),
    ]
